company/urls.py
# coding: utf8

from django.conf.urls import url
from django.views.generic import TemplateView
from .views import CompanyList, CompanyCreate, CompanyUpdate, CompanyLeadersUpdateView, CompanyUpdateEKCDaEKTC, \
    GenericInfoDetail, GenericInfoUpdate, CompanyDelete, login_view, logout_view, DownloadStaffSubdivisionView, \
    QuestionView, StaffPositionProfessionView, StaffView, UpdateCasesView, AddPositionView, AddProfessionView, \
    EmployeePositionView, EmployeeProfessionView, StaffCreate, StaffUpdate, StaffDelete, ActivityDetail, \
    get_categories_and_list_position, get_ranks_and_list_work_professions, StaffSurnameUpdateView, AllCasesFormView, \
    StaffPosStaffProfUpdateView, FactorProductionView, StaffUpdateView, InstructionWorkerView, CompanySubdivisionUpdateView

urlpatterns = [
    url(r'^$', CompanyList.as_view(), name='list'),
    url(r'^add/$', CompanyCreate.as_view(), name='add'),
    url(r'^update/(?P<pk>[0-9]+)/$', CompanyUpdate.as_view(), name='update'),
    url(r'^update_leaders/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/$', CompanyLeadersUpdateView.as_view(), name='update_leaders'),
    url(r'^update_ekcd_ektc/(?P<pk>[0-9]+)/$', CompanyUpdateEKCDaEKTC.as_view(), name='update_ekcd_ektc'),
    url(r'^generic_info/detail/(?P<pk>[0-9]+)/$', GenericInfoDetail.as_view(), name='generic_info_detail'),
    url(r'^generic_info/update/(?P<pk>[0-9]+)/$', GenericInfoUpdate.as_view(), name='generic_info_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', CompanyDelete.as_view(), name='delete'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^download_staff/(?P<pk>[0-9]+)/$', DownloadStaffSubdivisionView.as_view(), name='staff_subdivision_download'),
    url(r'^question/(?P<division>[\w-]+)/(?P<pk>[0-9]+)/$', QuestionView.as_view(), name='question'),
    url(r'^position_profession/(?P<pk>[0-9]+)/$', StaffPositionProfessionView.as_view(), name='position_profession'),
    url(r'^staff_detail/(?P<pk>[0-9]+)/$', StaffView.as_view(), name='staff_detail'),
    url(r'^change_cases/(?P<pk>[0-9]+)/$', UpdateCasesView.as_view(), name='change_cases'),
    url(r'^add_position/(?P<pk>[0-9]+)/$', AddPositionView.as_view(), name='add_position'),
    url(r'^add_profession/(?P<pk>[0-9]+)/$', AddProfessionView.as_view(), name='add_profession'),
    url(r'^employee_position/(?P<pk>[0-9]+)/$', EmployeePositionView.as_view(), name='employee_position'),
    url(r'^employee_profession/(?P<pk>[0-9]+)/$', EmployeeProfessionView.as_view(), name='employee_profession'),
    url(r'^employee/create/$', StaffCreate.as_view(), name='employee_add'),
    url(r'^employee/(?P<pk>[0-9]+)/$', StaffUpdate.as_view(), name='employee_update'),
    url(r'^employee/(?P<pk>[0-9]+)/delete/$', StaffDelete.as_view(), name='employee_delete'),
    url(r'^dynamic_category_select/$', get_categories_and_list_position, name='dynamic_category_select'),
    url(r'^dynamic_rank_select/$', get_ranks_and_list_work_professions, name='dynamic_rank_select'),
    url(r'^activity/(?P<pk>[0-9]+)/$', ActivityDetail.as_view(), name='activity'),
    url(r'^staff_surname/(?P<pk>[0-9]+)/$', StaffSurnameUpdateView.as_view(), name='staff_surname'),
    url(r'^staff_pos_prof/$', StaffPosStaffProfUpdateView.as_view(), name='staff_pos_prof'),
    url(r'^all_cases/(?P<section>[\w-]+)/$', AllCasesFormView.as_view(), name='all_cases'),
    url(r'^check_pos_prof/$', TemplateView.as_view(template_name='company/check_okrb.html'), name='check_pos_prof'),
    url(r'^factors_production/$', FactorProductionView.as_view(), name='factors_production'),
    url(r'^staff/update/$', StaffUpdateView.as_view(), name='staff_update'),
    url(r'^staff/instructions/$', InstructionWorkerView.as_view(), name='worker_instructions'),
    url(r'^subdivision/(?P<pk>[0-9]+)/$', CompanySubdivisionUpdateView.as_view(), name='subdivision_update')
]

fire_safety/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^auto/$', autocomplete, name='autocomplete'),
    url(r'^dynamic_employee/$', get_profession, name='dynamic'),
    url(r'^instructions/$', InstructionView.as_view(), name='instructions'),
    url(r'^(?P<section>[\w-]+)/$', ManyDocumentCreate.as_view(), name='list'),
    url(r'^(?P<section>[\w-]+)/data_filing/$', DataFiling.as_view(), name='data_filing'),
    url(r'^(?P<section>[\w-]+)/(?P<pk>[0-9]+)/$', DocumentCreate.as_view(), name='create'),


]

mayor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import View, TemplateView, DetailView
from django.http import HttpRequest, HttpResponse
from fire_safety.models import FireDocument, ReadyDocument
from company.models import Company
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin
from work_safety.models import OTDocument, ReadyOTDocument
from electrical_safety.models import ElSafetyDocument, ReadyElSafetyDocument
from ecology.models import ReadyECDocument, ECDocument
import debug_toolbar


class DocumentView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(FireDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyDocument, company=obj, fire_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentOTView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(OTDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyOTDocument, company=obj, ot_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentELView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ElSafetyDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyElSafetyDocument, company=obj, el_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentECView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ECDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyECDocument, company=obj, ec_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', 1000))

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^$',  TemplateView.as_view(template_name="base.html"), name='home'),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^fire/', include('fire_safety.urls', namespace='fire')),
    url(r'^ot/', include('work_safety.urls', namespace='work-safety')),
    url(r'^electrical/', include('electrical_safety.urls', namespace='electrical_safety')),
    url(r'^ecology/', include('ecology.urls', namespace='ecology')),
    url(r'^ptm/', include('ptm.urls', namespace='ptm')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/fire/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentView.as_view(), name='doc'),
    url(r'^media/ot/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentOTView.as_view(), name='doc_ot'),
    url(r'^media/electrical/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentELView.as_view(), name='doc_el'),
    url(r'^media/ec/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentECView.as_view(), name='doc_ec'),
]

ptm/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^staff/$', KindPTM.as_view(), name='kind_ptm'),
    url(r'^instruction/$', InstructionsView.as_view(), name='instruction'),
    url(r'^generic_ptm/(?P<pk>[0-9]+)/$', CompanyInfoUpdateView.as_view(), name='generic_ptm'),
    url(r'^boss_ptm/(?P<pk>[0-9]+)/$', BossPTMView.as_view(), name='boss_ptm'),
    url(r'^create_ptm/$', CreatePTMView.as_view(), name='create_ptm'),

]

fire_safety/models.py
# coding: utf8
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from company.models import *
from django.core.files.storage import FileSystemStorage
import os


class FireDocument(models.Model):
    FIRE_SCROLL = 'scroll'
    FIRE_ORDER = 'order'
    FIRE_INSTRUCTION = 'instruction'
    FIRE_PROGRAM = 'program'
    FIRE_PROVISION = 'provision'
    OTHER = 'other'
    SECTIONS = (
        (FIRE_SCROLL, 'перечени'),
        (FIRE_ORDER, 'приказы'),
        (FIRE_INSTRUCTION, 'инструкции'),
        (FIRE_PROGRAM, 'программы'),
        (FIRE_PROVISION, 'положения'),
        (OTHER, 'остальное'),
    )

    document_code = models.IntegerField(unique=True, null=True)
    related_fields = models.ManyToManyField('FieldInDocument', blank=True, related_name='related_field')
    title = models.CharField(max_length=300, default=u'первый')
    path = models.FilePathField(blank=True, null=True, max_length=300, path=settings.FILE_PATH_FIRE_DOCUMENT,
                                recursive=True)
    section = models.CharField(max_length=100, choices=SECTIONS, default=FIRE_ORDER)
    default_document = models.BooleanField('Стандартно необходимый документ', default=False)

    def __str__(self):
        return "{} {}".format(self.document_code, self.title)

    def get_absolute_url(self):
        return reverse('fire:create', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = u'Документы пожарной безопасности'
        verbose_name_plural = u'Документы пожарной безопасности'


class FieldInDocument(models.Model):
    F1 = 'F1'
    F2 = 'F2'
    F3 = 'F3'
    F4 = 'F4'
    F41 = 'F41'
    F5 = 'F5'
    F6 = 'F6'
    F7 = 'F7'
    F8 = 'F8'
    F9 = 'F9'
    F10 = 'F10'
    F11 = 'F11'
    F12 = 'F12'
    F13 = 'F13'
    FIELDS = (
        (F1, u'F1 от пт'),
        (F2, u'F2 инженерные системы'),
        (F3, u'F3 дополнительный параграф'),
        (F4, u'F4 фио'),
        (F41, u'F41 фио или ничего'),
        (F5, u'F5 фио структурное подразделение'),
        (F6, u'F6 согласовавшие'),
        (F7, u'F7 дата документа'),
        (F8, u'F8 номер документа'),
        (F9, u'F9 фио формсет'),
        (F10, u'F10 помещения формсет'),
        (F11, u'F11 да нет'),
        (F12, u'F12 фио телефон'),
        (F13, u'F13 фио структурные подразделения'),
    )
    document = models.ForeignKey(FireDocument, related_name='fields')
    label = models.TextField(max_length=300, blank=True)
    field_name = models.CharField(max_length=100, choices=FIELDS, default=F1)
    prefix = models.CharField(max_length=100, blank=True)
    position_number = models.IntegerField(blank=True, null=True)
    index_number = models.IntegerField('Порядковый номер поля на форме', blank=True, null=True)
    required_field = models.BooleanField('Необходимое поле?', blank=True, default=False)

    def __str__(self):
        return '{}, {}, {}, {}'.format(self.document.title, self.field_name, self.prefix, self.label)

    class Meta:
        verbose_name = u'Поля в документах'
        verbose_name_plural = u'Поля в документах'


class Subdivision(models.Model):
    company = models.ForeignKey('company.Company')
    title = models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        verbose_name = u'Название подразделение'
        verbose_name_plural = u'Названия подразделений'


class Field(models.Model):
    P1 = 'технического оборудования'
    P2 = 'вентиляционных систем и систем кондиционирования воздуха'
    P3 = 'средств связи и оповещения'
    P4 = 'отопительных систем'
    P5 = 'электроустановок молниезащитных и заземляющих устройств'
    P6 = 'технических средств противопожарной защиты'
    PLACES = (
        (P1, 'технического оборудования'),
        (P2, 'вентиляционных систем и систем кондиционирования воздуха'),
        (P3, 'средств связи и оповещения'),
        (P4, 'отопительных систем'),
        (P5, 'электроустановок, молниезащитных и заземляющих устройств'),
        (P6, 'технических средств противопожарной защиты'),
    )
    FIRE_SAFETY = 'пожарной безопасности'
    PROTECTION_WORK = 'охране труда'
    FIRE_WORK = (
        (FIRE_SAFETY, 'пожарной безопасности'),
        (PROTECTION_WORK, 'охране труда'),
    )
    field_name = models.CharField(max_length=255, choices=FieldInDocument.FIELDS, default=FieldInDocument.FIELDS[0])
    company = models.ForeignKey('company.Company', blank=True, null=True)
    document = models.ForeignKey(FireDocument, blank=True, null=True)
    position_number = models.IntegerField(blank=True, null=True)
    label = models.CharField(max_length=300, blank=True)
    # field's name
    fs_pt = models.CharField('пт или от', max_length=30, choices=FIRE_WORK, default=FIRE_SAFETY)
    system = MultiSelectField(max_length=255, blank=True, choices=PLACES)
    paragraph = models.TextField('дополнительный пункт', max_length=400, blank=True)
    employee = models.ForeignKey('company.Staff', blank=True, null=True, verbose_name='сотрудник')
    # if employee have some professions in this field we save one of them that use in this field
    staff_profession = models.ForeignKey(StaffProfession, blank=True, null=True, verbose_name='профессия')
    staff_position = models.ForeignKey(StaffPosition, blank=True, null=True, verbose_name='должность')
    subdivision = models.ForeignKey(Subdivision, verbose_name='Подразделение',  null=True)
    subdivisions = models.ManyToManyField(Subdivision, verbose_name='Подразделения', related_name='subs')
    date = models.CharField(u'дата подписи', max_length=255, blank=True)
    document_number = models.CharField(u'номер документа', max_length=255, blank=True)
    room = models.CharField(u'помещение', max_length=255)
    trigger = models.BooleanField(u'Да Нет', max_length=255, blank=True, default=False)
    phone_number = models.CharField(u'номер телефона', max_length=255)

    class Meta:
        verbose_name = u'Поле'
        verbose_name_plural = u'Поля'

    def __str__(self):
        return '{} {} {} {}'.format(self.company, self.document, self.field_name, self.position_number)


class OverwriteStorage(FileSystemStorage):

    def get_available_name(self, name, max_length=None):
        name = name.replace('_', ' ')
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name
fs = OverwriteStorage(location=settings.MEDIA_ROOT)


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/company_<id>/fire_<section>/document_<id>/<filename>
    return 'fire/{}/{}/{}/{}'.format(
        instance.company.id, instance.fire_document.section, instance.fire_document.id, filename
    )


class ReadyDocument(models.Model):
    company = models.ForeignKey(Company)
    fire_document = models.ForeignKey(FireDocument)
    pdf_file = models.FileField(upload_to=user_directory_path, storage=fs, max_length=350)
    word_file = models.FileField(upload_to=user_directory_path, blank=True)

    def __str__(self):
        return '{} {}'.format(self.company, self.fire_document)

templates/fire_safety/data_filing.html
{% extends 'base.html' %}
{% load static %}
{% block documents_section %}
    <div class="col-md-2">
        {% if request.user.is_authenticated %}
            <div class="panel panel-default">
                <div class="panel-heading">Документы пожарной безопасности</div>
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'fire:list' 'order' %}">Приказы</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'scroll' %}">Перечни</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'instruction' %}">Инструкции</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'program' %}">Программы</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'provision' %}">Положения</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <div class="col-md-10">
        <form role="form" method="post" action="{% url 'fire:data_filing' section %}">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Отправить">
        </form>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static "fire_safety/hide_show_element.js" %}"></script>
    <script src="{% static "bootstrap_3/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "fire_safety/select.js" %}"></script>
    <script src="{% static "bootstrap_3/js/defaults-ru_RU.min.js" %}"></script>
{% endblock %}

templates/fire_safety/instruction.html
{% extends "base.html" %}
{% block documents_section %}
{% endblock %}
{% block about_company %}
{% endblock %}
{% block content %}
    <div id="first" class="row" style=" padding-bottom: 50px;">
        <div id="button1" class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'company:generic_info_detail' request.user.genericinfocompany.pk %}" role="button"
               class="btn btn-md btn-primary">
                Общая информация
            </a>
        </div>
    </div>
    <div class="row" style="padding-bottom: 50px">
    <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'company:position_profession' request.user.pk %}" role="button"
               class="btn btn-md btn-primary">
                Указать проф/долж. сотрудников/Добавить сотрудника</a></div>
    </div>
    <div class="row" style="padding-bottom: 50px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'company:update' request.user.pk %}" role="button"
               class="btn btn-md btn-primary">
                Указать разработчиков(инструкций, положений, программ)</a>
        </div>
    </div>
        <div class="row" style="padding-bottom: 50px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'company:update_leaders' request.user.pk 'fire' %}" role="button"
               class="btn btn-md btn-primary">
                Указать руководящие должности</a>
        </div>
    </div>
    <div class="row" style="padding-bottom: 50px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'company:all_cases' 'fire' %}" role="button"
               class="btn btn-md btn-primary">
                Проверить падежи</a></div>
    </div>
    <div class="row" style="padding-bottom: 50px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'company:question' 'fire_safety' request.user.pk %}" role="button"
               class="btn btn-md btn-primary">
                Вопросы по Пожарной Безопасности</a></div>
    </div>
    <div class="row" style="padding-bottom: 50px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'fire:list' 'order' %}" role="button"
               class="btn btn-md btn-primary">
                Сформировать документы по ПБ</a>
        </div>
    </div>

{% endblock %}

templates/fire_safety/list.html
{% extends 'base.html' %}
{% load static %}
{% block documents_section %}
    <div class="col-md-2">
        {% if request.user.is_authenticated %}
            <div class="panel panel-default">
                <div class="panel-heading">Документы пожарной безопасности</div>
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'fire:list' 'order' %}">Приказы</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'scroll' %}">Перечни</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'instruction' %}">Инструкции</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'program' %}">Программы</a>
                    <a class="list-group-item" href="{% url 'fire:list' 'provision' %}">Положения</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block content %}
    <div class="col-md-10">

        <table class="table  table-hover table-condensed">
            <thead>
            <tr>
                <th>№</th>
                <th class="text-center">Наименование документа</th>
                <th class="text-center">Предпросмотр</th>
            </tr>
            </thead>

            {% for document, ready in documents %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td class="{% if ready %}success{% else %}warning{% endif %}">
                        <a href="{% url 'fire:create' section document.pk %}">{{ document }}</a>
                    </td>
                    {% if ready %}
                        <td class="success">
                            {% url 'doc' request.user.pk section document.id as pdf_document_url %}
                            <button href="{{ pdf_document_url }}" class="btn-xs btn-success preview">Смотреть</button>
                        </td>
                    {% else %}
                        <td class="warning">
                            <button type="button" class="btn btn-xs btn-warning">Не сформирован</button>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}

        </table>

        <button class="btn btn-primary" data-toggle="modal" data-target="#modalCreateDocuments">
            Сформировать документы
        </button>
        <a href="{% url 'fire:data_filing' section %}">
            <button class="btn btn-success">Заполнить даты документов
            </button>
        </a>
        <div class="modal fade" id="modalCreateDocuments" tabindex="-1" role="dialog"
             aria-labelledby="myLargeModalLabel"
             aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <form role="form" method="post" action="{% url 'fire:list' section %}">{% csrf_token %}
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Создание документов</h4>
                        </div>
                        <div class="modal-body">
                            <p>Выберите из списка документы, которые вы хотите сформировать</p>
                            {{ form.as_p }}
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-primary" value="Отправить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static "fire_safety/hide_show_element.js" %}"></script>
    <script src="{% static "bootstrap_3/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "fire_safety/select.js" %}"></script>
    <script src="{% static "bootstrap_3/js/defaults-ru_RU.min.js" %}"></script>
    <script src="{% static "fire_safety/pdf_in_modal.js" %}"></script>
    <script src="{% static "fire_safety/ajax_post.js" %}"></script>
    <script src="{% static "fire_safety/ajax_csrf.js" %}"></script>
    <script src="{% static "fire_safety/informer.js" %}"></script>
    <script src="{% static "fire_safety/dynamic_employee.js" %}"></script>
    <script src="{% static "fire_safety/pdf_in_modal_link.js" %}"></script>

{% endblock %}