company/urls.py
# coding: utf8

from django.conf.urls import url
from django.views.generic import TemplateView
from .views import CompanyList, CompanyCreate, CompanyUpdate, CompanyLeadersUpdateView, CompanyUpdateEKCDaEKTC, \
    GenericInfoDetail, GenericInfoUpdate, CompanyDelete, login_view, logout_view, DownloadStaffSubdivisionView, \
    QuestionView, StaffPositionProfessionView, StaffView, UpdateCasesView, AddPositionView, AddProfessionView, \
    EmployeePositionView, EmployeeProfessionView, StaffCreate, StaffUpdate, StaffDelete, ActivityDetail, \
    get_categories_and_list_position, get_ranks_and_list_work_professions, StaffSurnameUpdateView, AllCasesFormView, \
    StaffPosStaffProfUpdateView, FactorProductionView, StaffUpdateView, InstructionWorkerView, CompanySubdivisionUpdateView

urlpatterns = [
    url(r'^$', CompanyList.as_view(), name='list'),
    url(r'^add/$', CompanyCreate.as_view(), name='add'),
    url(r'^update/(?P<pk>[0-9]+)/$', CompanyUpdate.as_view(), name='update'),
    url(r'^update_leaders/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/$', CompanyLeadersUpdateView.as_view(), name='update_leaders'),
    url(r'^update_ekcd_ektc/(?P<pk>[0-9]+)/$', CompanyUpdateEKCDaEKTC.as_view(), name='update_ekcd_ektc'),
    url(r'^generic_info/detail/(?P<pk>[0-9]+)/$', GenericInfoDetail.as_view(), name='generic_info_detail'),
    url(r'^generic_info/update/(?P<pk>[0-9]+)/$', GenericInfoUpdate.as_view(), name='generic_info_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', CompanyDelete.as_view(), name='delete'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^download_staff/(?P<pk>[0-9]+)/$', DownloadStaffSubdivisionView.as_view(), name='staff_subdivision_download'),
    url(r'^question/(?P<division>[\w-]+)/(?P<pk>[0-9]+)/$', QuestionView.as_view(), name='question'),
    url(r'^position_profession/(?P<pk>[0-9]+)/$', StaffPositionProfessionView.as_view(), name='position_profession'),
    url(r'^staff_detail/(?P<pk>[0-9]+)/$', StaffView.as_view(), name='staff_detail'),
    url(r'^change_cases/(?P<pk>[0-9]+)/$', UpdateCasesView.as_view(), name='change_cases'),
    url(r'^add_position/(?P<pk>[0-9]+)/$', AddPositionView.as_view(), name='add_position'),
    url(r'^add_profession/(?P<pk>[0-9]+)/$', AddProfessionView.as_view(), name='add_profession'),
    url(r'^employee_position/(?P<pk>[0-9]+)/$', EmployeePositionView.as_view(), name='employee_position'),
    url(r'^employee_profession/(?P<pk>[0-9]+)/$', EmployeeProfessionView.as_view(), name='employee_profession'),
    url(r'^employee/create/$', StaffCreate.as_view(), name='employee_add'),
    url(r'^employee/(?P<pk>[0-9]+)/$', StaffUpdate.as_view(), name='employee_update'),
    url(r'^employee/(?P<pk>[0-9]+)/delete/$', StaffDelete.as_view(), name='employee_delete'),
    url(r'^dynamic_category_select/$', get_categories_and_list_position, name='dynamic_category_select'),
    url(r'^dynamic_rank_select/$', get_ranks_and_list_work_professions, name='dynamic_rank_select'),
    url(r'^activity/(?P<pk>[0-9]+)/$', ActivityDetail.as_view(), name='activity'),
    url(r'^staff_surname/(?P<pk>[0-9]+)/$', StaffSurnameUpdateView.as_view(), name='staff_surname'),
    url(r'^staff_pos_prof/$', StaffPosStaffProfUpdateView.as_view(), name='staff_pos_prof'),
    url(r'^all_cases/(?P<section>[\w-]+)/$', AllCasesFormView.as_view(), name='all_cases'),
    url(r'^check_pos_prof/$', TemplateView.as_view(template_name='company/check_okrb.html'), name='check_pos_prof'),
    url(r'^factors_production/$', FactorProductionView.as_view(), name='factors_production'),
    url(r'^staff/update/$', StaffUpdateView.as_view(), name='staff_update'),
    url(r'^staff/instructions/$', InstructionWorkerView.as_view(), name='worker_instructions'),
    url(r'^subdivision/(?P<pk>[0-9]+)/$', CompanySubdivisionUpdateView.as_view(), name='subdivision_update')
]

electrical_safety/urls.py
# coding: utf8
from django.conf.urls import include, url
from .views import *


urlpatterns = [
    url(r'^instructions/$', ElInstructionView.as_view(), name='instructions'),
    url(r'^create_document/(?P<pk>[0-9]+)/$', DocumentCreate.as_view(), name='create_document',),
    url(r'^create_document/chain/(?P<q_pk>[0-9]+)/$', ChainDocumentCreate.as_view(), name='create_in_chain',),
    url(r'^create_document/el/$', CreateDocumentsElView.as_view(), name='create_document_el',),
    url(r'^update_leaders/(?P<pk>[0-9]+)/$', ElectricalLeadersUpdateView.as_view(), name='update_leaders',),
    url(r'^list/$', DocumentList.as_view(), name='list',),
]

mayor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import View, TemplateView, DetailView
from django.http import HttpRequest, HttpResponse
from fire_safety.models import FireDocument, ReadyDocument
from company.models import Company
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin
from work_safety.models import OTDocument, ReadyOTDocument
from electrical_safety.models import ElSafetyDocument, ReadyElSafetyDocument
from ecology.models import ReadyECDocument, ECDocument
import debug_toolbar


class DocumentView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(FireDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyDocument, company=obj, fire_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentOTView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(OTDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyOTDocument, company=obj, ot_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentELView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ElSafetyDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyElSafetyDocument, company=obj, el_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentECView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ECDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyECDocument, company=obj, ec_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', 1000))

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^$',  TemplateView.as_view(template_name="base.html"), name='home'),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^fire/', include('fire_safety.urls', namespace='fire')),
    url(r'^ot/', include('work_safety.urls', namespace='work-safety')),
    url(r'^electrical/', include('electrical_safety.urls', namespace='electrical_safety')),
    url(r'^ecology/', include('ecology.urls', namespace='ecology')),
    url(r'^ptm/', include('ptm.urls', namespace='ptm')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/fire/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentView.as_view(), name='doc'),
    url(r'^media/ot/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentOTView.as_view(), name='doc_ot'),
    url(r'^media/electrical/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentELView.as_view(), name='doc_el'),
    url(r'^media/ec/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentECView.as_view(), name='doc_ec'),
]

ptm/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^staff/$', KindPTM.as_view(), name='kind_ptm'),
    url(r'^instruction/$', InstructionsView.as_view(), name='instruction'),
    url(r'^generic_ptm/(?P<pk>[0-9]+)/$', CompanyInfoUpdateView.as_view(), name='generic_ptm'),
    url(r'^boss_ptm/(?P<pk>[0-9]+)/$', BossPTMView.as_view(), name='boss_ptm'),
    url(r'^create_ptm/$', CreatePTMView.as_view(), name='create_ptm'),

]

electrical_safety/models.py
# coding: utf8
from __future__ import unicode_literals
from django.conf import settings
from company.models import *
from django.core.files.storage import FileSystemStorage
import os

from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from fire_safety.models import Company
from mayor.settings import FINISHED_DOCUMENT


class ElSafetyDocument(models.Model):

    ELECTRICAL = 'electrical'
    SECTIONS_DOC = (
        (ELECTRICAL, 'Электробезопасность'),
    )

    document_code = models.IntegerField(unique=True, null=True)
    related_fields = models.ManyToManyField('FieldInDocument', blank=True, related_name='related_field')
    title = models.CharField(max_length=300, default='первый')
    path = models.FilePathField(blank=True, null=True, max_length=300, path=settings.FILE_PATH_ELECTRICAL_DOCUMENT,
                                recursive=True)
    section_document = models.CharField(max_length=100, choices=SECTIONS_DOC, default=ELECTRICAL, blank=True)
    default_document = models.BooleanField('Стандартно необходимый документ', default=False)

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        verbose_name = 'Документ электробезопасности'
        verbose_name_plural = 'Документы электобезопасности'


class FieldInDocument(models.Model):
    F3 = 'F3'
    F4 = 'F4'
    F41 = 'F41'
    F6 = 'F6'
    F7 = 'F7'
    F8 = 'F8'
    F12 = 'F12'
    FIELDS = (
        (F3, 'F3 дополнительный параграф'),
        (F4, 'F4 фио'),
        (F41, 'F41 фио или ничего'),
        (F6, 'F6 согласовавшие'),
        (F7, 'F7 дата документа'),
        (F8, 'F8 номер документа'),
        (F12, 'F12 pdf файл'),
    )
    document = models.ForeignKey(ElSafetyDocument, related_name='fields')
    label = models.TextField(max_length=300, blank=True)
    field_name = models.CharField(max_length=100, choices=FIELDS, default=F41)
    prefix = models.CharField(max_length=100, blank=True)
    position_number = models.IntegerField(blank=True, null=True)
    index_number = models.IntegerField('Порядковый номер поля на форме', blank=True, null=True)
    required_field = models.BooleanField('Необходимое поле?', blank=True, default=False)
    element_chain = models.BooleanField('Поле для цепочки вопросов', blank=True, default=False)
    default = models.BooleanField('Поле по умолчанию', blank=True, default=False)

    def __str__(self):
        return '{}, {}, {}, {}'.format(self.document.title, self.field_name, self.prefix, self.label)

    class Meta:
        verbose_name = 'Поле в документе'
        verbose_name_plural = 'Поля в документах'


def generate_filename(self, filename):
    from mayor.settings import FINISHED_DOCUMENT
    alphabet = [chr(x) for x in range(256, 10000) if 'а' <= chr(x) <= 'я' or 'А' <= chr(x) <= 'Я']
    name_document = '{}.pdf'.format(self.document.__str__())
    company_folder_name = ''
    for letter in self.company.genericinfocompany.short_title:
        if letter in alphabet:
            company_folder_name += letter

    folder_for_finished_document = '{0}{1}/{2}'.format(
        FINISHED_DOCUMENT, company_folder_name, self.document.section_document)
    if not os.path.exists(folder_for_finished_document):
        os.makedirs(folder_for_finished_document)
    document_pdf = '{0}/{1}/{2}'.format(
        company_folder_name, self.document.section_document, name_document)
    if os.path.exists(os.path.abspath('{}{}'.format(FINISHED_DOCUMENT, document_pdf))):
        os.remove(os.path.abspath('{}{}'.format(FINISHED_DOCUMENT, document_pdf)))
    return document_pdf


class PDFStorage(FileSystemStorage):
    pass


custom_fs = PDFStorage(location=FINISHED_DOCUMENT, base_url='/static/image_documents/')


class FieldElSafety(models.Model):

    field_name = models.CharField(max_length=255, choices=FieldInDocument.FIELDS, default=FieldInDocument.FIELDS[0])
    company = models.ForeignKey('company.Company', blank=True, null=True)
    document = models.ForeignKey(ElSafetyDocument, blank=True, null=True)
    position_number = models.IntegerField(blank=True, null=True)
    label = models.CharField(max_length=255, blank=True)
    # field's name
    employee = models.ForeignKey('company.Staff', blank=True, null=True, verbose_name='сотрудник')
    date = models.CharField('дата подписи', max_length=255, blank=True)
    document_number = models.CharField('номер документа', max_length=255, blank=True)
    paragraph = models.TextField('дополнительный пункт', max_length=800, blank=True)
    trigger = models.BooleanField('Да Нет', max_length=255, blank=True, default=False)
    pdf_file = models.FileField(upload_to=generate_filename, storage=custom_fs, null=True)
    # if employee have some professions in this field we save one of them that use in this field
    staff_profession = models.ForeignKey(StaffProfession, blank=True, null=True, verbose_name='профессия')
    staff_position = models.ForeignKey(StaffPosition, blank=True, null=True, verbose_name='должность')

    class Meta:
        verbose_name = 'Поле'
        verbose_name_plural = 'Поля'

    def __str__(self):
        return '{} {} {} {}'.format(self.company, self.document, self.field_name, self.position_number)


class ElectricalStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        name = name.replace('_', ' ')
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name


fs = ElectricalStorage(location=settings.MEDIA_ROOT)


def el_document_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/company_<id>/ot_<section>/document_<id>/<filename>
    return 'electrical/{}/{}/{}/{}'.format(
        instance.company.id, instance.el_document.section_document, instance.el_document.id, filename
    )


class ReadyElSafetyDocument(models.Model):
    company = models.ForeignKey(Company)
    el_document = models.ForeignKey(ElSafetyDocument)
    pdf_file = models.FileField(upload_to=el_document_directory_path, storage=fs, max_length=350)
    word_file = models.FileField(upload_to=el_document_directory_path, blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.company, self.el_document)

templates/electrical_safety/create_documents_el.html
{% extends 'base.html' %}
{% load static %}
{% block button_back %}
{% endblock %}
{% block about_company %}
    <div class="progress progress-striped active">
        <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            0%
        </div>
    </div>
    <h3 id="time-download" class="text-center"></h3>
    <form role="form" method="post" action=".">{% csrf_token %}
        <input type="button" id="submit" value="Сформировать документы по ОТ" class="submit btn btn-success"/>
    </form>
{% endblock %}
{% block button %}
{% endblock %}
{% block documents_section %}
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        $('#time-download').hide();
        var submit_ajax = function () {
            $('#submit').attr({'disabled': "disabled"});
            $.ajax({
                url: "{% url 'electrical_safety:create_document_el' %}",
                dataType: "json",
                type: 'POST',
                success: function (data) {
                    var progress_bar = $('#progress-bar');
                    var percent = data['percent'];
                    progress_bar.text(percent + '%').attr({'style': 'width: ' + percent + '%'});
                    if ((data['percent'] < 100)) {
                        submit_ajax();
                    } else if ((percent === 100)) {
                        progress_bar.text('100%').attr({'style': 'width: 100%'});
                        $('#time-download').text('время обработки документов ' + data['time'] + ' с.').show("slow");
                        $('#submit').removeAttr('disabled');
                    }
                },
                error: function (data) {
                    alert('Произошла ошибка, попробуйте перезагрузить страницу');
                    $('#submit').removeAttr('disabled');
                }
            });
        };
        $('#submit').click(submit_ajax)
    </script>
    <script type="application/javascript" src="{% static "fire_safety/ajax_csrf.js" %}"></script>
{% endblock %}

templates/electrical_safety/create_in_chain.html
{% extends 'electrical_safety/create.html' %}
{% block button_back %}
{% endblock %}
{% block about_test %}
    <style>
        .dropdown-menu {
            min-width: 200px;
        }

        .dropdown-menu.columns-2 {
            min-width: 400px;
        }

        .dropdown-menu.columns-3 {
            min-width: 600px;
        }

        .dropdown-menu li a {
            padding: 5px 15px;
            font-weight: 300;
        }

        .multi-column-dropdown {
            list-style: none;
        }

        .multi-column-dropdown li a {
            display: block;
            clear: both;
            line-height: 1.428571429;
            color: #333;
            white-space: normal;
        }

        .multi-column-dropdown li a:hover {
            text-decoration: none;
            color: #262626;
            background-color: #f5f5f5;
        }

        @media (max-width: 767px) {
            .dropdown-menu.multi-column {
                min-width: 240px !important;
                overflow-x: hidden;
            }
        }
    </style>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="alert alert-danger"><strong>{{ message|safe }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="row">
        <div class="col-md-4" role="group">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class=" dropdown dropdown-toggle" data-toggle="dropdown">Вопрос {{ q_pk }} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu multi-column columns-2">
                            <div class="row">
                                {% for document, ready in documents_chain %}
                                    {% if forloop.counter == 1 or forloop.counter == 9 %}
                                        <div class="col-sm-6">
                                        <ul class="multi-column-dropdown">
                                    {% endif %}
                                <li><a {% if ready %}style="color: #449d44"{% endif %}
                                       href="{% url 'electrical_safety:create_in_chain' forloop.counter0 %}">Вопрос {{ forloop.counter }}</a>
                                </li>
                                {% if forloop.counter == 8 or forloop.last %}
                                    </ul>
                                    </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-4 col-md-offset-4">
            <a href="{% url 'electrical_safety:instructions' %}" class="btn btn-sm btn-primary" role="button">
                Инструкции к заполнению по Электробезопасности
            </a>
        </div>
    </div>

    <h3 class="text-center" style="color: #428BCA">Вам осталось ответить на {{ questions_remain }} вопросов</h3>
{% endblock %}
{% block button %}
{% endblock %}

templates/electrical_safety/elsafetydocument_list.html
{% extends 'base.html' %}
{% load static %}
{% block documents_section %}
{% endblock %}
{% block content %}
    <div class="col-md-10">

        <table class="table  table-hover table-condensed">
            <thead>
            <tr>
                <th>№</th>
                <th class="text-center">Наименование документа</th>
                <th class="text-center">Предпросмотр</th>
            </tr>
            </thead>

            {% for document, ready in documents %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td class="{% if ready %}success{% else %}warning{% endif %}">
                        <a href="{% url 'electrical_safety:create_document' document.pk %}">{{ document }}</a>
                    </td>
                    {% if ready %}
                        <td class="success">
                        {% url 'doc_el' request.user.pk document.section_document document.id as pdf_document_url %}
                        <button href="{{ pdf_document_url }}" class="btn btn-xs btn-success preview">Смотреть</button>
                        </td>
                    {% else %}
                        <td class="warning">
                            <button type="button" class="btn btn-xs btn-warning">Не сформирован</button>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}

        </table>

    </div>

{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static "fire_safety/hide_show_element.js" %}"></script>
    <script src="{% static "bootstrap_3/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "fire_safety/select.js" %}"></script>
    <script src="{% static "bootstrap_3/js/defaults-ru_RU.min.js" %}"></script>
    <script src="{% static "fire_safety/pdf_in_modal.js" %}"></script>
    <script src="{% static "fire_safety/ajax_post.js" %}"></script>
    <script src="{% static "fire_safety/ajax_csrf.js" %}"></script>
    <script src="{% static "fire_safety/informer.js" %}"></script>
    <script src="{% static "fire_safety/dynamic_employee.js" %}"></script>
    <script src="{% static "fire_safety/pdf_in_modal_link.js" %}"></script>

{% endblock %}

templates/electrical_safety/instructions_user.html
{% extends "base.html" %}
{% block documents_section %}
{% endblock %}
{% block about_company %}
{% endblock %}
{% block content %}
    <div id="first" class="row" style=" padding-bottom: 70px;">
        <div id="button1" class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'company:generic_info_update' request.user.genericinfocompany.pk %}" role="button"
               class="btn btn-lg {% if generic_info %} btn-success {% else %} btn-danger {% endif  %}">
                Общая информация
            </a>
        </div>
    </div>
    <div class="row" style="padding-bottom: 70px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'electrical_safety:update_leaders' request.user.pk %}" role="button"
               class="btn btn-lg {% if leaders %} btn-success {% else %} btn-danger {% endif  %}">
                Указать руководящие должности</a>
        </div>
    </div>
    <div class="row" style="padding-bottom: 70px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'electrical_safety:create_in_chain' '0' %}" role="button"
               class="btn btn-lg {% if test %} btn-success {% else %} btn-danger {% endif  %}">
                Вопросы по Электробезопасности</a></div>
    </div>
    <div class="row" style="padding-bottom: 70px">
        <div class="col-md-4 col-md-offset-4 text-center">
            <a href="{% url 'electrical_safety:create_document_el' %}" role="button"
               class="btn btn-lg btn-primary">
                Сформировать документы по ОТ</a>
        </div>
    </div>

{% endblock %}

templates/electrical_safety/update_leaders.html
{% extends 'company/update_leaders.html' %}
{% block about_company %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="alert alert-danger"><strong>{{ message|safe }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="row">
        <div class="col-md-4 col-md-offset-7">
            <a href="{% url 'electrical_safety:instructions' %}" class="btn btn-sm btn-primary" role="button">
                Страница подготовки к формирования документов по Электробезопасности
            </a>
        </div>
    </div>
{% endblock %}