company/urls.py
# coding: utf8

from django.conf.urls import url
from django.views.generic import TemplateView
from .views import CompanyList, CompanyCreate, CompanyUpdate, CompanyLeadersUpdateView, CompanyUpdateEKCDaEKTC, \
    GenericInfoDetail, GenericInfoUpdate, CompanyDelete, login_view, logout_view, DownloadStaffSubdivisionView, \
    QuestionView, StaffPositionProfessionView, StaffView, UpdateCasesView, AddPositionView, AddProfessionView, \
    EmployeePositionView, EmployeeProfessionView, StaffCreate, StaffUpdate, StaffDelete, ActivityDetail, \
    get_categories_and_list_position, get_ranks_and_list_work_professions, StaffSurnameUpdateView, AllCasesFormView, \
    StaffPosStaffProfUpdateView, FactorProductionView, StaffUpdateView, InstructionWorkerView, CompanySubdivisionUpdateView

urlpatterns = [
    url(r'^$', CompanyList.as_view(), name='list'),
    url(r'^add/$', CompanyCreate.as_view(), name='add'),
    url(r'^update/(?P<pk>[0-9]+)/$', CompanyUpdate.as_view(), name='update'),
    url(r'^update_leaders/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/$', CompanyLeadersUpdateView.as_view(), name='update_leaders'),
    url(r'^update_ekcd_ektc/(?P<pk>[0-9]+)/$', CompanyUpdateEKCDaEKTC.as_view(), name='update_ekcd_ektc'),
    url(r'^generic_info/detail/(?P<pk>[0-9]+)/$', GenericInfoDetail.as_view(), name='generic_info_detail'),
    url(r'^generic_info/update/(?P<pk>[0-9]+)/$', GenericInfoUpdate.as_view(), name='generic_info_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', CompanyDelete.as_view(), name='delete'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^download_staff/(?P<pk>[0-9]+)/$', DownloadStaffSubdivisionView.as_view(), name='staff_subdivision_download'),
    url(r'^question/(?P<division>[\w-]+)/(?P<pk>[0-9]+)/$', QuestionView.as_view(), name='question'),
    url(r'^position_profession/(?P<pk>[0-9]+)/$', StaffPositionProfessionView.as_view(), name='position_profession'),
    url(r'^staff_detail/(?P<pk>[0-9]+)/$', StaffView.as_view(), name='staff_detail'),
    url(r'^change_cases/(?P<pk>[0-9]+)/$', UpdateCasesView.as_view(), name='change_cases'),
    url(r'^add_position/(?P<pk>[0-9]+)/$', AddPositionView.as_view(), name='add_position'),
    url(r'^add_profession/(?P<pk>[0-9]+)/$', AddProfessionView.as_view(), name='add_profession'),
    url(r'^employee_position/(?P<pk>[0-9]+)/$', EmployeePositionView.as_view(), name='employee_position'),
    url(r'^employee_profession/(?P<pk>[0-9]+)/$', EmployeeProfessionView.as_view(), name='employee_profession'),
    url(r'^employee/create/$', StaffCreate.as_view(), name='employee_add'),
    url(r'^employee/(?P<pk>[0-9]+)/$', StaffUpdate.as_view(), name='employee_update'),
    url(r'^employee/(?P<pk>[0-9]+)/delete/$', StaffDelete.as_view(), name='employee_delete'),
    url(r'^dynamic_category_select/$', get_categories_and_list_position, name='dynamic_category_select'),
    url(r'^dynamic_rank_select/$', get_ranks_and_list_work_professions, name='dynamic_rank_select'),
    url(r'^activity/(?P<pk>[0-9]+)/$', ActivityDetail.as_view(), name='activity'),
    url(r'^staff_surname/(?P<pk>[0-9]+)/$', StaffSurnameUpdateView.as_view(), name='staff_surname'),
    url(r'^staff_pos_prof/$', StaffPosStaffProfUpdateView.as_view(), name='staff_pos_prof'),
    url(r'^all_cases/(?P<section>[\w-]+)/$', AllCasesFormView.as_view(), name='all_cases'),
    url(r'^check_pos_prof/$', TemplateView.as_view(template_name='company/check_okrb.html'), name='check_pos_prof'),
    url(r'^factors_production/$', FactorProductionView.as_view(), name='factors_production'),
    url(r'^staff/update/$', StaffUpdateView.as_view(), name='staff_update'),
    url(r'^staff/instructions/$', InstructionWorkerView.as_view(), name='worker_instructions'),
    url(r'^subdivision/(?P<pk>[0-9]+)/$', CompanySubdivisionUpdateView.as_view(), name='subdivision_update')
]

fire_safety/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^auto/$', autocomplete, name='autocomplete'),
    url(r'^dynamic_employee/$', get_profession, name='dynamic'),
    url(r'^instructions/$', InstructionView.as_view(), name='instructions'),
    url(r'^(?P<section>[\w-]+)/$', ManyDocumentCreate.as_view(), name='list'),
    url(r'^(?P<section>[\w-]+)/data_filing/$', DataFiling.as_view(), name='data_filing'),
    url(r'^(?P<section>[\w-]+)/(?P<pk>[0-9]+)/$', DocumentCreate.as_view(), name='create'),


]

mayor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import View, TemplateView, DetailView
from django.http import HttpRequest, HttpResponse
from fire_safety.models import FireDocument, ReadyDocument
from company.models import Company
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin
from work_safety.models import OTDocument, ReadyOTDocument
from electrical_safety.models import ElSafetyDocument, ReadyElSafetyDocument
from ecology.models import ReadyECDocument, ECDocument
import debug_toolbar


class DocumentView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(FireDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyDocument, company=obj, fire_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentOTView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(OTDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyOTDocument, company=obj, ot_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentELView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ElSafetyDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyElSafetyDocument, company=obj, el_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentECView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ECDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyECDocument, company=obj, ec_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', 1000))

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^$',  TemplateView.as_view(template_name="base.html"), name='home'),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^fire/', include('fire_safety.urls', namespace='fire')),
    url(r'^ot/', include('work_safety.urls', namespace='work-safety')),
    url(r'^electrical/', include('electrical_safety.urls', namespace='electrical_safety')),
    url(r'^ecology/', include('ecology.urls', namespace='ecology')),
    url(r'^ptm/', include('ptm.urls', namespace='ptm')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/fire/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentView.as_view(), name='doc'),
    url(r'^media/ot/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentOTView.as_view(), name='doc_ot'),
    url(r'^media/electrical/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentELView.as_view(), name='doc_el'),
    url(r'^media/ec/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentECView.as_view(), name='doc_ec'),
]

ptm/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^staff/$', KindPTM.as_view(), name='kind_ptm'),
    url(r'^instruction/$', InstructionsView.as_view(), name='instruction'),
    url(r'^generic_ptm/(?P<pk>[0-9]+)/$', CompanyInfoUpdateView.as_view(), name='generic_ptm'),
    url(r'^boss_ptm/(?P<pk>[0-9]+)/$', BossPTMView.as_view(), name='boss_ptm'),
    url(r'^create_ptm/$', CreatePTMView.as_view(), name='create_ptm'),

]

templates/company/all_cases.html
{% extends 'base.html' %}
{% load static %}
{% block about_company %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="alert alert-danger"><strong>{{ message|safe }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'fire:instructions' %}" class="btn btn-sm btn-info" role="button">
                Страница подготовки к формирования документов по Пб
            </a>
        </div>
        <div class="col-md-4 col-md-offset-4">
            <a href="{% url 'work-safety:instructions' %}" class="btn btn-sm btn-primary" role="button">
                Страница подготовки к формирования документов по ОТ
            </a>
        </div>
    </div>

{% endblock %}

{% block documents_section %}
{% endblock %}
{% block content %}
    <style>
        input[type="checkbox"] {
            width: 20px; /*Desired width*/
            height: 20px; /*Desired height*/
        }
    </style>
    <h4>Наведите курсор на флажок и вы увидите соответствующие автоматичеси сформированные падежи, если они верны отметьте,
    если нет нажмите кнопку исправить и введите правильные формы слова(В выпадаемом списке падежей фамилии людей должны быть с загловной буквы,
        название проф./долж. со строчной, размер букв в падежах фирмы должен быть таким же как в тексте). Необходимо отметить
    все слова иначе вы не сможете сформировать документы
    </h4>
    <div class="row">
    <p class="text-center"><button id="filling_all" class="btn btn-danger">Выделить все</button></p>
        <form method="post" role="form" action=".">{% csrf_token %}
            {{ form.management_form }}
            {% for f in form %}
                {{ f.id }}
                <label>{{ f.checked.errors }}</label>
                <div class="form-group" style="padding-bottom: 12px">
                    <div>
                        <div class="col-md-6">
                            {{ f.nomn.help_text }}

                        </div>
                        <div class="col-md-1">

                            <span data-toggle="tooltip" class="span_input_case" data-placement="bottom"
                                  title="
{{ f.nomn.value }}
{{ f.gent.value }}
{{ f.datv.value }}
{{ f.accs.value }}
{{ f.ablt.value }}
{{ f.loct.value }}">
                    {{ f.checked }}
                    </span>
                        </div>
                        <div class="col-md-5">
                            <a role="button" class="btn btn-xs btn-primary fix_case"> Исправить</a>

                            <a role="button" class="btn btn-xs btn-success fixed_case" style="display: none">
                                Исправлено</a>
                        </div>
                    </div>
                    {{ f.nomn.errors }}
                    {{ f.nomn }}
                    {{ f.gent.errors }}
                    {{ f.gent }}
                    {{ f.datv.errors }}
                    {{ f.datv }}
                    {{ f.accs.errors }}
                    {{ f.accs }}
                    {{ f.ablt.errors }}
                    {{ f.ablt }}
                    {{ f.loct.errors }}
                    {{ f.loct }}

                </div>
            {% endfor %}
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary" value="Отправить">
            </div>

        </form>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">$('.popover_cases').popover()</script>
    <script type="text/javascript">

        $('.fix_case').on('click', function () {
            var href = $(this);
            var inputs = href.parentsUntil('.form-group').nextAll('input');
            $(this).next('a').show();
            inputs.each(function (indx, element) {
                $(element).removeAttr('type');
            });
        });
        $('.fixed_case').on('click', function () {
            var href = $(this);
            var inputs = href.parentsUntil('.form-group').nextAll('input');
            inputs.each(function (indx, element) {
                $(element).attr({'type': 'hidden'});
            });
            href.parent().prev().find('input').attr({"checked": "checked"});
            href.hide();
        });
        $('#filling_all').on('click', function () {
            $('input[type=checkbox]').each(function(indx, element) {
                $(element).prop('checked', 'true')
            })
        });
    </script>
{% endblock %}

templates/company/list.html
{% extends 'base.html' %}
{% block documents_section %}
{% endblock %}
{% block content %}
    <div class="col-md-12">
        <ul class="list-group">
            {% for company, info in company_generic_info %}
                <li class="list-group-item list-group-item-success">
                {% if current_info_id == info.id or not request.user.is_authenticated %}
                    {% if user.is_authenticated %}
                        <a href="{% url 'company:generic_info_detail' info.id %}">
                    {% else %}
                        <a href="{% url 'company:login' %}?login={{ company }}">
                    {% endif %}
                        <h5>Логин:<strong>{{ company }}</strong>, Короткое название:{{ info.short_title }}</h5>
                    </a>
                {% else %}
                    <h5>Логин:<strong>{{ company }}</strong>, Короткое название:{{ info.short_title }}</h5>
                {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/company/question.html
{% extends 'base.html' %}
{% load static %}
{% block documents_section %}
{% endblock %}
{% block about_company %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="alert alert-danger"><strong>{{ message|safe }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="row" style="padding-bottom: 20px">
        <div class="col-md-4">
            <a href="{% url 'fire:instructions' %}" class="btn btn-sm btn-info" role="button">
                Страница подготовки к формирования документов по ПБ
            </a>
        </div>
        <div class="col-md-4 col-md-offset-4">
            <a href="{% url 'work-safety:instructions' %}" class="btn btn-sm btn-primary" role="button">
                Страница подготовки к формирования документов по ОТ
            </a>
        </div>
    </div>

{% endblock %}
{% block content %}
    <style> .popover {
        font-size: 12px;
    }</style>

    <div class="col-md-12">
        <form role="form" method="post" action=".">{% csrf_token %}
            {{ form.management_form }}
            {% for f in form %}
                {{ f.id }}
                <ul>
                    <label>
                        <small>
                            {% for x in question_text %}
                                {% if x.0 == f.id.value %}
                                    {{ x.1 }}
                                {% endif %}
                            {% endfor %}
                            {% if f.answer.help_text %}
                                <button type="button" class="btn btn-info btn-xs example" data-container="body"
                                        data-toggle="popover"
                                        data-placement="right"
                                        data-content="{{ f.answer.help_text }}">
                                    Подсказка
                                </button>
                            {% endif %}
                        </small>
                    </label>
                    <li>{{ f.question }}</li>
                    <li>{{ f.answer }}</li>
                </ul>
            {% endfor %}
            <ul>
                <li><input type="submit" class="btn btn-primary" value="Отправить"></li>
            </ul>
        </form>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            var select = $('.selectpicker_question');
            select.selectpicker({
                'actionsBox': 'true',
                'deselectAllText': 'Снять все выделения',
                'selectAllText': 'Выделить все',
                'liveSearch': true,
                'liveSearchPlaceholder': null,
                'liveSearchStyle': 'contains',
                'dropupAuto': false
            }).on('loaded.bs.select', function (e) {
                var size = 130;
                sel = $(this).prev().find('.text');
                for (i = 0; i < sel.length; i++) {
                    newsContent = $(sel[i]);
                    newsText = newsContent.text();
                    if (newsText.length > size) {
                        newsContent.attr("data-toggle", "tooltip");
                        newsContent.attr("data-placement", "left");
                        newsContent.attr("title", newsText);
                        newsContent.text(newsText.slice(0, size) + ' ...');
                    }
                }
            });
        });
    </script>
    <script src="{% static "fire_safety/informer.js" %}"></script>
    <script src="{% static "bootstrap_3/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "fire_safety/select.js" %}"></script>
    <script src="{% static "bootstrap_3/js/defaults-ru_RU.min.js" %}"></script>
    <script>
        $(document).ready(function () {
            {% for f in form %}
                    $('.selectpicker_question').eq(
                            {{ forloop.counter0 }}).selectpicker('val', '{{ f.instance.answer }}'.split(' ')
                    );
            {% endfor %}
        });
    </script>
{% endblock %}

templates/company/short_title_case.html
<span class="glyphicon glyphicon-zoom-in" data-toggle="tooltip" data-placement="right"
      title="
{{ data.short_title_case.nomn }}
{{ data.short_title_case.gent }}
{{ data.short_title_case.datv }}
{{ data.short_title_case.accs }}
{{ data.short_title_case.ablt }}
{{ data.short_title_case.loct }}
"></span>
{% url 'company:change_cases' data.short_title_case.id as url %}
<a href="{{ url }}">
    <span class="glyphicon glyphicon-cog" data-toggle="tooltip" data-placement="right"></span>
</a>

templates/company/staff_detail.html
{% extends 'base.html' %}
{% load keyvalue %}
{% block documents_section %}
{% endblock %}
{% block about_company %}
    <div class="panel panel-info">
        <div class="panel-heading"><strong>Редактировать должности, профессии сотрудников</strong></div>
        <div class="panel-body">
            Вы считаете что указали всех сотрудников и таблица внизу полностью соответсвует вашему штатному расписанию
            и теперь неплохо бы указать для них соответствующие профессии и должности тогд вам
            <a href="{% url 'company:position_profession' request.user.pk %}">сюда</a>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading"><strong>Сформировать документы</strong></div>
        <div class="panel-body">
            У вас идеальное штатное: указаны все острудники(таблица снизу) и для каждого из них указана
            <a href="{% url 'company:position_profession' request.user.pk %}">соответсвующая должность или профессия.</a>
            Вы хотите преступить к заполнению документов <a href="{% url 'work-safety:instructions'%}">по охране труда</a>
            или <a href="{% url 'fire:instructions'%}">пожарной безопасности</a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="col-md-12">
    <a class="btn btn-sm btn-success" href="{% url "company:employee_add" %}" role="button">Добавить еще сотрудника</a>
    <a class="btn btn-sm btn-success" href="{% url "company:staff_surname" request.user.pk %}" role="button">Редактировать сотрудников</a>
    <a class="btn btn-sm btn-success" href="{% url "company:staff_update" %}" role="button">Редактировать данные о сотрудниках</a>
    <h2 class="text-center">Таблица информации о сотрудниках и то как они будут спрягаться в тексте документов</h2>
        <table class="table table-striped table-bordered">

            <tr>
                <td class="text-center col-xs-1" rowspan="2">№</td>
                <td class="text-center col-xs-5" colspan="3"><strong>СОТРУДНИКИ</strong></td>
                <td class="text-center col-xs-6" colspan="2"><strong>ПАДЕЖИ</strong></td>
            </tr>
            <tr>
                <td class="text-center"><strong>Фамилия инициалы</strong></td>
                <td class="text-center"><strong>Редактировать</strong></td>
                <td class="text-center"><strong>Удалить</strong></td>
                <td class="text-center"><strong>Формы слова</strong></td>
                <td class="text-center"><strong>Редактировать</strong></td>
            </tr>
            {% for person in staff %}
                <tr>
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center">{{ person.surname }} {{ person.initials }} (id={{ person.id }})</td>
                    <td class="text-center"><a class="btn btn-primary btn-xs"
                                               href="{% url "company:employee_update" person.pk %}" role="button">Да</a>
                    </td>
                    <td class="text-center"><a class="btn btn-primary btn-xs"
                                               href="{% url "company:employee_delete" person.pk %}" role="button">Да</a>
                    </td>
                    <td class="text-center {% if not person.case_id %}danger{% endif %}">
                        <button type="button" class="btn btn-default popover_cases btn-xs" data-html="true"
                                data-content="{{ cases|kv:person.case_id|kv:'nomn' }}<br>
                                {{ cases|kv:person.case_id|kv:'gent' }}<br>{{ cases|kv:person.case_id|kv:'datv' }}<br>
                                {{ cases|kv:person.case_id|kv:'accs' }}<br>{{ cases|kv:person.case_id|kv:'ablt' }}<br>
                                {{ cases|kv:person.case_id|kv:'loct' }}">
                            {% if person.case_id %}Падежи {{ person.surname }}{% else %}Падежи не указаны{% endif %}
                        </button>

                    </td>
                    <td class="text-center">
                        {% url "company:change_cases" person.case_id as case_url %}
                        <a class="btn btn-primary btn-xs" href="{{ case_url }}"
                           role="button">Изменить</a></td>


                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">$('.popover_cases').popover()</script>
{% endblock %}

templates/company/staff_position.html
{% extends 'base.html' %}
{% load static %}
{% block documents_section %}
{% endblock %}
{% block fire %}
    <style>
        .ui-autocomplete {
            max-height: 400px;
            overflow-y: auto; /* prevent horizontal scrollbar */
            overflow-x: hidden; /* add padding to account for vertical scrollbar */
            z-index: 1000 !important;
        }
    </style>
    <p>Если вы не смогли выбрать подходящую для вас должность(должности) из нашего списка
        (допустим вы не нашли "оператор ЭВМ") вы можете <a href="{% url 'company:add_position' request.user.pk %}">добавить свою должность(должности)</a>  к нашему списку.
    </p>
    <div class="col-md-12">
        <form method="post" role="form" action=".">{% csrf_token %}
            {{ form.management_form }}
            {{ form.non_form_errors }}
            {% for f in form %}
                {{ f.id }}
                <div class="inline {{ form.prefix }}">

                    {{ f.employee_position.errors }}
                    {{ f.employee_position }}

                    {{ f.position_visible_in_form.errors }}
                    {{ f.position_visible_in_form }}

                    {{ f.category.errors }}
                    {{ f.category.label_tag }}
                    {{ f.category }}

                    {{ f.derivative_position.errors }}
                    {{ f.derivative_position.label_tag }}
                    {{ f.derivative_position }}

                    {{ f.DELETE }}
                </div>
            {% endfor %}
            <div class="form-group">
                <input type="submit" value="Отправить" class="btn btn-primary btn-sm submit"/>
            </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static "fire_safety/autocomplete.js" %}"></script>
    <script src="{% static "bootstrap_3/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "fire_safety/select.js" %}"></script>
    <script src="{% static "bootstrap_3/js/defaults-ru_RU.min.js" %}"></script>
{% endblock %}

templates/company/staff_update_form.html
{% extends 'base.html' %}
{% load static %}
{% block documents_section %}
{% endblock %}
{% block content %}
    <div class="col-md-12">
        <a type="button" role="button" class="btn btn-primary"
           href="{% url 'company:staff_detail' request.user.pk %}">Назад</a>

        <form role="form" class="form-inline" method="post" action=".">{% csrf_token %}
            <table class="table table-bordered table-condensed">
                <thead>
                <tr>
                    <th class="text-center">№</th>
                    <th class="text-center">ФИО</th>
                    <th class="text-center">Пол</th>
                    <th class="text-center">Дата рождения</th>
                    <th class="text-center">Место жительства</th>

                </tr>
                </thead>
                {{ form.management_form }}
                {% for f in form %}
                    {{ f.id }}
                    <tr>
                        <td align="center">
                            {{ forloop.counter }}
                        </td>
                        <td>
                            <strong>{{ f.instance.surname }}
                            {{ f.instance.initials }}</strong>(id={{ f.instance.id }})<br>
{#                            ({{ f.instance.staff }})#}
                        </td>
                        <td align="center">
                            {{ f.sex }}
                        </td>
                        <td align="center">
                            {{ f.date_birthday }}
                        </td>
                        <td align="center">
                            {{ f.place_residence }}
                        </td>

                    </tr>
                {% endfor %}

            </table>


            <input type="submit" class="btn btn-primary" value="Отправить">
        </form>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'fire_safety/add.js' %}"></script>
{% endblock %}

templates/company/update_staff_fio.html
{% extends 'base.html' %}
{% load static %}
{% block documents_section %}
{% endblock %}
{% block content %}
    <div class="col-md-12">
    <a type="button" role="button" class="btn btn-primary"
               href="{% url 'company:staff_detail' request.user.pk %}">Назад</a>
        <form role="form" class="form-inline" method="post" action=".">{% csrf_token %}
            <div class="form-group">
                <div><label>Фамилия инициалы сотрудников</label></div>
                {{ form.management_form }}
                {{ form.non_form_errors }}
                {% for f in form %}
                    {{ f.id }}

                    <div class="form-group inline {{ form.prefix }}">

                        {{ f.surname.errors }}
                        {{ f.surname.label_tag }}
                        {{ f.surname }}

                        {{ f.initials.errors }}
                        {{ f.initials.label_tag }}
                        {{ f.initials }}

                        {{ f.employment_date.errors }}
                        {{ f.employment_date.label_tag }}
                        {{ f.employment_date }}

                        <div>{{ f.DELETE }}</div>
                    </div>

                {% endfor %}
            </div>
            <input type="submit" class="btn btn-primary" value="Отправить">
        </form>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'fire_safety/add.js' %}"></script>
{% endblock %}