company/urls.py
# coding: utf8

from django.conf.urls import url
from django.views.generic import TemplateView
from .views import CompanyList, CompanyCreate, CompanyUpdate, CompanyLeadersUpdateView, CompanyUpdateEKCDaEKTC, \
    GenericInfoDetail, GenericInfoUpdate, CompanyDelete, login_view, logout_view, DownloadStaffSubdivisionView, \
    QuestionView, StaffPositionProfessionView, StaffView, UpdateCasesView, AddPositionView, AddProfessionView, \
    EmployeePositionView, EmployeeProfessionView, StaffCreate, StaffUpdate, StaffDelete, ActivityDetail, \
    get_categories_and_list_position, get_ranks_and_list_work_professions, StaffSurnameUpdateView, AllCasesFormView, \
    StaffPosStaffProfUpdateView, FactorProductionView, StaffUpdateView, InstructionWorkerView, CompanySubdivisionUpdateView

urlpatterns = [
    url(r'^$', CompanyList.as_view(), name='list'),
    url(r'^add/$', CompanyCreate.as_view(), name='add'),
    url(r'^update/(?P<pk>[0-9]+)/$', CompanyUpdate.as_view(), name='update'),
    url(r'^update_leaders/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/$', CompanyLeadersUpdateView.as_view(), name='update_leaders'),
    url(r'^update_ekcd_ektc/(?P<pk>[0-9]+)/$', CompanyUpdateEKCDaEKTC.as_view(), name='update_ekcd_ektc'),
    url(r'^generic_info/detail/(?P<pk>[0-9]+)/$', GenericInfoDetail.as_view(), name='generic_info_detail'),
    url(r'^generic_info/update/(?P<pk>[0-9]+)/$', GenericInfoUpdate.as_view(), name='generic_info_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', CompanyDelete.as_view(), name='delete'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^download_staff/(?P<pk>[0-9]+)/$', DownloadStaffSubdivisionView.as_view(), name='staff_subdivision_download'),
    url(r'^question/(?P<division>[\w-]+)/(?P<pk>[0-9]+)/$', QuestionView.as_view(), name='question'),
    url(r'^position_profession/(?P<pk>[0-9]+)/$', StaffPositionProfessionView.as_view(), name='position_profession'),
    url(r'^staff_detail/(?P<pk>[0-9]+)/$', StaffView.as_view(), name='staff_detail'),
    url(r'^change_cases/(?P<pk>[0-9]+)/$', UpdateCasesView.as_view(), name='change_cases'),
    url(r'^add_position/(?P<pk>[0-9]+)/$', AddPositionView.as_view(), name='add_position'),
    url(r'^add_profession/(?P<pk>[0-9]+)/$', AddProfessionView.as_view(), name='add_profession'),
    url(r'^employee_position/(?P<pk>[0-9]+)/$', EmployeePositionView.as_view(), name='employee_position'),
    url(r'^employee_profession/(?P<pk>[0-9]+)/$', EmployeeProfessionView.as_view(), name='employee_profession'),
    url(r'^employee/create/$', StaffCreate.as_view(), name='employee_add'),
    url(r'^employee/(?P<pk>[0-9]+)/$', StaffUpdate.as_view(), name='employee_update'),
    url(r'^employee/(?P<pk>[0-9]+)/delete/$', StaffDelete.as_view(), name='employee_delete'),
    url(r'^dynamic_category_select/$', get_categories_and_list_position, name='dynamic_category_select'),
    url(r'^dynamic_rank_select/$', get_ranks_and_list_work_professions, name='dynamic_rank_select'),
    url(r'^activity/(?P<pk>[0-9]+)/$', ActivityDetail.as_view(), name='activity'),
    url(r'^staff_surname/(?P<pk>[0-9]+)/$', StaffSurnameUpdateView.as_view(), name='staff_surname'),
    url(r'^staff_pos_prof/$', StaffPosStaffProfUpdateView.as_view(), name='staff_pos_prof'),
    url(r'^all_cases/(?P<section>[\w-]+)/$', AllCasesFormView.as_view(), name='all_cases'),
    url(r'^check_pos_prof/$', TemplateView.as_view(template_name='company/check_okrb.html'), name='check_pos_prof'),
    url(r'^factors_production/$', FactorProductionView.as_view(), name='factors_production'),
    url(r'^staff/update/$', StaffUpdateView.as_view(), name='staff_update'),
    url(r'^staff/instructions/$', InstructionWorkerView.as_view(), name='worker_instructions'),
    url(r'^subdivision/(?P<pk>[0-9]+)/$', CompanySubdivisionUpdateView.as_view(), name='subdivision_update')
]

electrical_safety/urls.py
# coding: utf8
from django.conf.urls import include, url
from .views import *


urlpatterns = [
    url(r'^instructions/$', ElInstructionView.as_view(), name='instructions'),
    url(r'^create_document/(?P<pk>[0-9]+)/$', DocumentCreate.as_view(), name='create_document',),
    url(r'^create_document/chain/(?P<q_pk>[0-9]+)/$', ChainDocumentCreate.as_view(), name='create_in_chain',),
    url(r'^create_document/el/$', CreateDocumentsElView.as_view(), name='create_document_el',),
    url(r'^update_leaders/(?P<pk>[0-9]+)/$', ElectricalLeadersUpdateView.as_view(), name='update_leaders',),
    url(r'^list/$', DocumentList.as_view(), name='list',),
]

fire_safety/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^auto/$', autocomplete, name='autocomplete'),
    url(r'^dynamic_employee/$', get_profession, name='dynamic'),
    url(r'^instructions/$', InstructionView.as_view(), name='instructions'),
    url(r'^(?P<section>[\w-]+)/$', ManyDocumentCreate.as_view(), name='list'),
    url(r'^(?P<section>[\w-]+)/data_filing/$', DataFiling.as_view(), name='data_filing'),
    url(r'^(?P<section>[\w-]+)/(?P<pk>[0-9]+)/$', DocumentCreate.as_view(), name='create'),


]

mayor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import View, TemplateView, DetailView
from django.http import HttpRequest, HttpResponse
from fire_safety.models import FireDocument, ReadyDocument
from company.models import Company
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin
from work_safety.models import OTDocument, ReadyOTDocument
from electrical_safety.models import ElSafetyDocument, ReadyElSafetyDocument
from ecology.models import ReadyECDocument, ECDocument
import debug_toolbar


class DocumentView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(FireDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyDocument, company=obj, fire_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentOTView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(OTDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyOTDocument, company=obj, ot_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentELView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ElSafetyDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyElSafetyDocument, company=obj, el_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', None))


class DocumentECView(UserPassesTestMixin, DetailView):
    content_type = 'application/pdf'
    model = Company

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        document = get_object_or_404(ECDocument, id=int(kwargs.get('document_id', 1000)))
        ready_document = get_object_or_404(ReadyECDocument, company=obj, ec_document=document)
        return HttpResponse(ready_document.pdf_file.file, content_type="application/pdf")

    def test_func(self):
        return self.request.user.pk == int(self.kwargs.get('pk', 1000))

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^$',  TemplateView.as_view(template_name="base.html"), name='home'),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^fire/', include('fire_safety.urls', namespace='fire')),
    url(r'^ot/', include('work_safety.urls', namespace='work-safety')),
    url(r'^electrical/', include('electrical_safety.urls', namespace='electrical_safety')),
    url(r'^ecology/', include('ecology.urls', namespace='ecology')),
    url(r'^ptm/', include('ptm.urls', namespace='ptm')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/fire/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentView.as_view(), name='doc'),
    url(r'^media/ot/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentOTView.as_view(), name='doc_ot'),
    url(r'^media/electrical/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentELView.as_view(), name='doc_el'),
    url(r'^media/ec/(?P<pk>[0-9]+)/(?P<section>[\w-]+)/(?P<document_id>[\w-]+)/', DocumentECView.as_view(), name='doc_ec'),
]

ptm/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^staff/$', KindPTM.as_view(), name='kind_ptm'),
    url(r'^instruction/$', InstructionsView.as_view(), name='instruction'),
    url(r'^generic_ptm/(?P<pk>[0-9]+)/$', CompanyInfoUpdateView.as_view(), name='generic_ptm'),
    url(r'^boss_ptm/(?P<pk>[0-9]+)/$', BossPTMView.as_view(), name='boss_ptm'),
    url(r'^create_ptm/$', CreatePTMView.as_view(), name='create_ptm'),

]

work_safety/urls.py
# coding: utf8
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^siz/$', SizView.as_view(), name='siz',),
    url(r'^siz/list_works/$', WorksWithSizsView.as_view(), name='works_with_siz',),
    url(r'^siz/(?P<pk>[0-9]+)/$', ProfPosListView.as_view(), name='siz-list-prof-pos',),
    url(r'^siz/create/(?P<pk>[0-9]+)/$', SizCreateView.as_view(), name='siz-create',),
    url(r'^siz/update/$', SizUpdateView.as_view(), name='siz-update',),
    url(r'^create_document/(?P<pk>[0-9]+)/$', DocumentCreate.as_view(), name='create-document',),
    url(r'^create_document/chain/(?P<q_pk>[0-9]+)/$', ChainDocumentCreate.as_view(), name='create-document-chain',),
    url(r'^create_document/ot/$', CreateDocumentsOTView.as_view(), name='create-document-ot',),
    url(r'^section_(?P<section>[\w-]+)/$', TreeView.as_view(), name='list-document',),
    url(r'^section/(?P<section>[\w-]+)/$', get_documents_by_section, name='get-documents',),
    url(r'^data_filing/$', DataFilingView.as_view(), name='data_filing',),
    url(r'^download_documents/$', DownloadOTDocumentView.as_view(), name='download_documents'),
    url(r'^create_select_ot_docs/$', GenerateOTDocuments.as_view(), name='create_select_ot_docs'),
    url(r'^instructions/$', OTInstructionView.as_view(), name='instructions'),
    url(r'^medical_data/$', DownloadMedicalDataView.as_view(), name='medical_data'),
    url(r'^number_instructions/$', create_num_instructions, name='number_instructions'),
    url(r'^signed_documents/$', get_person_signed_document, name='signed_documents'),
    url(r'^update_field/(?P<pk>[0-9]+)/(?P<pk_doc>[0-9]+)/$', WorkFieldExcludeUpdateView.as_view(), name='update_field'),
]

templates/base.html
{% load static staticfiles %}
<!DOCTYPE html>
<html lang="ru">
{% block head %}
<head>
    <meta charset="utf-8">
    <title>Городничий</title>
    <link rel="shortcut icon" href="{% static "favicon.ico" %}">
    <link href="{% static "fire_safety/jquery-ui-1.11.4.custom/jquery-ui.min.css" %}" rel="stylesheet">
    <link href="{% static "fire_safety/jquery-ui-1.11.4.custom/jquery-ui.structure.min.css" %}" rel="stylesheet">
    <link href="{% static "fire_safety/jquery-ui-1.11.4.custom/jquery-ui.theme.min.css" %}" rel="stylesheet">
    <link href="{% static "fire_safety/styles/fire_safety.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap_3/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap_3/css/bootstrap-select.min.css" %}" rel="stylesheet">
    <link href="{% static "fire_safety/styles/bootstrap-treeview.css" %}" rel="stylesheet">
    <link href="{% static "fire_safety/styles/wickedpicker.css" %}" rel="stylesheet">
    <link href="{% static "lightbox/css/lightbox.min.css" %}" rel="stylesheet">
    <style>
        ul {
            list-style-type: none;
        }
        body { padding-bottom: 500px; }
    </style>
</head>
{% endblock %}
<body>
<div class="container">
    <nav class="navbar navbar-default row" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">ГОРОДНИЧИЙ</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav ">
                    <li><a href="{% url "home" %}">Главная</a></li>

                    <li><a href="{% url "company:list" %}">Спискок Компаний</a></li>
                    {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Сотрудники <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url "company:add_position" request.user.pk %}">Добавить новую должность</a>
                                </li>
                                <li><a href="{% url "company:add_profession" request.user.pk %}">Добавить новую профессию</a>
                                </li>
                                <li>
                                    <a href="{% url "company:staff_detail" request.user.pk %}">
                                        Редактировать <strong>персональные данные</strong> сотрудников
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url "company:position_profession" request.user.pk %}">
                                        Редактировать <strong>должность/профессию</strong> сотрудников
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url "work-safety:siz-list-prof-pos" request.user.pk %}">
                                        Редактироваь <strong>СИЗ</strong> должностей/профессий
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url "company:worker_instructions" %}">
                                        Указать <strong>инструкции</strong> для должностей/профессий
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url "company:check_pos_prof" %}">
                                        Проверить должности(профессии)
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url "work-safety:medical_data" %}">
                                        Загрузить информацию о мед. картах
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Документы <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url "fire:list" 'order' %}">Пожарная безопасность</a>
                                </li>
                                <li><a href="{% url "work-safety:list-document" 'overall' %}">Охрана труда</a></li>
                                <li><a href="{% url "electrical_safety:list" %}">Электробезопасность</a></li>
                                <li><a href="{% url "ecology:list" %}">Экология</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Фирма <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li role="presentation" class="dropdown-header">Общая информация</li>
                                <li><a href="{% url "company:generic_info_detail" request.user.genericinfocompany.pk %}">
                                    Данные о фирме(компании)</a>
                                </li>
                                <li><a href="{% url "company:update_leaders" request.user.pk 'work' %}">Рукводящие должности</a></li>
                                <li><a href="{% url "company:activity" request.user.pk %}">Виды деятельности</a></li>
                                <li><a href="{% url 'company:subdivision_update' request.user.pk %}">
                                    Подразделения(удалить/добавить)</a>
                                <li><a href="{% url 'company:update_ekcd_ektc' request.user.pk %}">ЕКСД ЕКТС</a>
                                <li><a href="{% url 'company:staff_subdivision_download' request.user.pk %}">Перезагрузить штатное</a>
                                </li>
                                <li><a href="{% url 'company:delete' request.user.pk %}">Удалить фирму</a>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation" class="dropdown-header">Охрана труда</li>
                                <li><a href="{% url "work-safety:instructions" %}"><strong>Инструкция как сформировать документы по ОТ</strong></a></li>
                                <li><a href="{% url "company:question" 'work_safety' request.user.pk %}">Вопросы
                                    охрана труда(ОТ)</a></li>
                                <li><a href="{% url "work-safety:create_select_ot_docs" %}">Сформровать выбранные документы</a></li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation" class="dropdown-header">Пожарная безопасность</li>
                                <li><a href="{% url "fire:instructions" %}"><strong>Инструкция как сформировать документы по ПБ</strong></a></li>
                                <li><a href="{% url "company:update" request.user.pk %}">Заполнить данные по пожарной безопасности</a></li>
                                <li><a href="{% url "company:question" 'fire_safety' request.user.pk %}">Вопросы
                                    пожарная безопасность</a></li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation" class="dropdown-header">Электробезопасность</li>
                                <li><a href="{% url "electrical_safety:instructions" %}"><strong>
                                    Инструкция как сформировать документы по Электробезопасности</strong></a></li>
                                <li><a href="{% url "electrical_safety:create_in_chain" 0 %}">Вопросы
                                    по электробезопасности</a></li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation" class="dropdown-header">Экология</li>
                                <li><a href="{% url "ecology:instruction" %}">
                                    <strong>Инструкция как сформировать документы по Экологии</strong></a></li>
                            </ul>
                        </li>
                        <li><a href="{% url "company:logout" %}">Выйти</a></li>
                        <li class="active"><a href="#">{{ request.user }}</a></li>

                    {% else %}
                        <li><a href="{% url "company:add" %}">Создать компанию</a></li>
                        <li><a href="{% url "company:check_pos_prof" %}">Проверить должности(профессии)</a></li>
                        <li><a href="{% url "company:login" %}">Войти</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="row">
        {% block about_test %}{% endblock %}
    </div>
    <div class="row">
        {% block about_company %}{% endblock %}
    </div>
    <div class="row">
        {% block documents_section %}
            <div id="section" class="col-md-4 col-md-offset-4" style="padding-top: 150px">
            <a href="{% url "fire:instructions" %}" class="btn btn-info btn-lg btn-block" role="button">Пожарная безопасность</a>
            <a href="{% url "work-safety:instructions" %}" class="btn btn-info btn-lg btn-block" role="button">Охрана труда</a>
            <a href="{% url "electrical_safety:instructions" %}" class="btn btn-info btn-lg btn-block" role="button">Электробезопасность</a>
            <a href="{% url "ecology:instruction" %}" class="btn btn-info btn-lg btn-block" role="button">Экология</a>
            <a href="{% url "company:check_pos_prof" %}" class="btn btn-primary btn-lg btn-block" role="button">
                Проверить должности(профессии)
            </a>
{#            <a href="{% url "outsourcing:all_elements" %}" class="btn btn-info btn-lg btn-block" role="button">Тестовый аутсортинг</a>#}
{#            <a href="{% url "ptm:instruction" %}" class="btn btn-info btn-lg btn-block" role="button">ПТМ</a>#}
            </div>
        {% endblock %}
        {% block fire %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>

</div>
</body>
{% block js %}
    <script src="{% static 'fire_safety/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'fire_safety/jquery-ui-1.11.4.custom/jquery-ui.min.js' %}"></script>
    <script src="{% static 'fire_safety/autocomplete.js' %}"></script>
    <script src="{% static 'fire_safety/jquery.formset2.js' %}"></script>
    <script src="{% static 'fire_safety/formset.js' %}"></script>
    <script src="{% static "bootstrap_3/js/bootstrap.min.js" %}"></script>
    <script src="{% static "lightbox/js/lightbox.min.js" %}"></script>
{% endblock %}
</html>